services:
  - type: web
    name: llm-deployment-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: STUDENT_API_PORT
        value: 3000
      - key: STUDENT_SECRET
        sync: false
      - key: STUDENT_EMAIL
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: openai
      - key: MAX_RETRIES
        value: 5
      - key: RETRY_DELAYS
        value: 1,2,4,8,16
      - key: REQUEST_TIMEOUT_MINUTES
        value: 10
